# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)


c1 = Country.create!(name: "Scotland", description: "Scotland, with its rich culinary heritage, has a diverse and flavorful food tradition that reflects its history and geographical influences. When it comes to bread and food in general, Scotland offers a range of unique and traditional dishes.")
c2 =Country.create!(name: "Japan", description: "Japan, with its rich culinary heritage, is celebrated for its meticulous preparation, diverse flavors, and a harmonious blend of tradition and innovation. Japanese cuisine, or washoku, is deeply rooted in seasonal ingredients, artistic presentation, and a respect for culinary craftsmanship. Here's a glimpse into Japanese food and bread.")
c3 =Country.create!(name: "Brazil", description: "Pão de queijo is a famous Brazilian cheese bread made with cassava flour and cheese, resulting in a chewy and cheesy delight.")
c4 =Country.create!(name: "France", description: "France is famed for its diverse bread offerings. Baguettes, with their crispy crust and soft interior, are a staple. Pain de campagne (country bread) and pain complet (whole wheat bread) are also popular. Each region has its own specialty, contributing to the rich tapestry of French bread.")
c5 =Country.create!(name: "India", description: "Naan and roti are traditional Indian bread varieties. Naan, leavened and often brushed with ghee, is baked in a tandoor. Roti is unleavened and cooked on a griddle. Paratha, a flaky and stuffed bread, is another popular choice.")
c6 =Country.create!(name: "Italy", description: "Italian bread is diverse and regionally influenced. Ciabatta, with its irregular holes and crisp crust, is popular. Focaccia, a flatbread often topped with herbs and olive oil, hails from Genoa. Grissini, thin and crunchy breadsticks, are another Italian favorite.")

c4.breads << Bread.create!(name: "Baguette", description: "A quintessential French bread, the baguette is characterized by its long, thin shape, crispy golden crust, and soft, airy interior. It is a symbol of French baking and is versatile, perfect for sandwiches or as an accompaniment to meals.", recipe: "Ingredients: -500g all-purpose flour 10g salt 7g active dry yeast 350ml warm water Instructions: In a bowl, dissolve yeast in warm water and let it sit for 5 minutes until foamy. In a large mixing bowl, combine flour and salt. Make a well in the center and pour in the yeast mixture. Mix until a dough forms, then knead on a floured surface for about 10 minutes until smooth. Place the dough in a lightly oiled bowl, cover with a cloth, and let it rise for 1-2 hours or until doubled in size. Punch down the dough, shape it into a baguette, and place on a baking sheet. Let it rise for another 30 minutes. Preheat the oven to 450°F (230°C). Slash the top of the baguette with a sharp knife and bake for 20-25 minutes until golden brown.", country_id: c4.id)
c4.breads << Bread.create!(name: "Pain de Campagne", description: "Translating to 'country bread', pain de campagne is a rustic French loaf made with a mix of flours. It has a chewy crust and a slightly tangy flavor, often enhanced by the addition of a natural sourdough starter.", recipe: "Ingredients: 400g bread flour 100g whole wheat flour 10g salt 300ml warm water 100g active sourdough starter Instructions: In a large bowl, combine bread flour, whole wheat flour, and salt. Mix warm water and sourdough starter, then add to the dry ingredients. Knead the dough for 15-20 minutes until it becomes smooth and elastic. Place the dough in a lightly oiled bowl, cover, and let it rise for 3-4 hours or until doubled in size. Shape the dough into a round loaf, place on a floured surface, and let it rise for an additional 1-2 hours. Preheat the oven to 450°F (230°C). Slash the top of the bread and bake for 30-35 minutes until the crust is golden brown.", country_id: c4.id)
c4.breads << Bread.create!(name: "Pain  Poilâne", description: "Pain Poilâne is a round, sourdough-style bread with a hearty crust and a distinct wheaty flavor. It's named after the renowned Poilâne bakery in Paris known for its commitment to traditional baking methods.", recipe: "Ingredients: 500g bread flour 10g salt 300ml warm water 100g active sourdough starter Instructions: Combine bread flour and salt in a large bowl. Mix warm water and sourdough starter, then add to the dry ingredients. Knead the dough for 15-20 minutes until smooth and elastic. Place the dough in a lightly oiled bowl, cover, and let it rise for 4-6 hours or until doubled.", country_id: c4.id)
c4.breads << Bread.create!(name: "Pain  Complet", description: "Pain complet, or whole wheat bread, is a wholesome and nutty-flavored French bread made with whole wheat flour. It offers a heartier texture and is a nutritious choice.", recipe: "Ingredients: 500g whole wheat flour 10g salt 7g active dry yeast 350ml warm water Instructions: Dissolve yeast in warm water and let it sit for 5 minutes until foamy. In a large bowl, combine whole wheat flour and salt. Make a well and pour in the yeast mixture. Mix until a dough forms, then knead on a floured surface for about 10 minutes until smooth. Place the dough in a lightly oiled bowl, cover, and let it rise for 1-2 hours or until doubled in size. Punch down the dough, shape it into a loaf, and place in a greased pan. Let it rise for another 30 minutes. Preheat the oven to 400°F (200°C). Bake for 25-30 minutes until the bread is golden brown.", country_id: c4.id)


